### ISSUE TITLE
组件部分没有显示

### ISSUE THREAD

**Issue by lmasdata** [greedying/vux-uploader#1]
你好，只是显示了title部分，其它的都隐藏了，请问是怎么回事
![image](https://cloud.githubusercontent.com/assets/8501594/24135881/31beae0a-0e47-11e7-9b28-62704a895326.png)
![image](https://cloud.githubusercontent.com/assets/8501594/24135894/3defc790-0e47-11e7-97e0-3dfb568793bf.png)

代码如下：
``` html
<template>
  <div>
    <uploader
      :max="varmax"
      :images="images"
      :upload-url="uploadUrl"
    ></uploader>
  </div>
</template>

<script>
  import Uploader from 'vux-uploader'

  export default {
    components: {
      Uploader
    },
    data() {
      return {
        varmax: 5,
        images: [],
        uploadUrl: ''
      }
    }
  }
</script>
```

**Comment by greedying** [comment]
readonly默认值的问题。
我写的是默认为true，这时候如果没有图片，那么图片和加减按钮就都不显示了。

我改成默认false。

**Comment by greedying** [comment]
已经发布0.1.2版本进行修复

**Comment by lmasdata** [comment]
@greedying 可以了 谢谢
