### ISSUE TITLE
autoUpload为false时，具体该怎么配置？

### ISSUE THREAD

**Issue by a24576946** [greedying/vux-uploader#18]
大神，你给的（含义: 选择图片后是否自动上传。是，则调用内部上传接口。否，则$emit('upload-image', formData)',formData`为图片内容，用户可监听事件自己上传）这段话，还有下面这段话，该怎么用（upload-image：emit时机: handleClick和autoUpload都为false`时，选择图片
参数: formData,图片内容生成的formData
备注: 可以通过vm.$refs.input获取图片的input元素）

**Comment by greedying** [comment]
请参考下vue文档哦。非vux-uploader内容

**Comment by beanLau** [comment]
有没有解决，求解决方法
