### ISSUE TITLE
选择图片就报错

### ISSUE THREAD

**Issue by handsomeslow** [greedying/vux-uploader#19]
代码片段：
<uploader :max="9" :handle-click="false" :show-header="false"
                :upload-url="uploadUrl" size="small" ></uploader>

输出：
vue.esm.js:579 [Vue warn]: Error in render: "TypeError: Cannot read property 'url' of undefined"

found in

---> <Uploader> at \**\node_modules\_vux-uploader@0.1.8@vux-uploader\src\components\uploader.vue

**Comment by greedying** [comment]
看下你的images格式是不是有问题

**Comment by handsomeslow** [comment]
images就一个空数组
<uploader :max="9" :images="images"
                    :handle-click="false" :show-header="false"
                    :upload-url="uploadUrl" size="small" >

data() {
  return {
     images:[]
  }
}

**Comment by greedying** [comment]
贴点代码看看？
