### ISSUE TITLE
安卓手机只能打开相册不能拍照

### ISSUE THREAD

**Issue by lmasdata** [greedying/vux-uploader#2]
如题，你好大神，请问有没有解决方法

**Comment by lmasdata** [comment]
加个这个属性就可以了
capture="camera"

**Comment by greedying** [comment]
好的，我加上~

**Comment by greedying** [comment]
已经发布v0.1.3版本。我调研了一下，这个capture属性不是很可靠，请谨慎使用

**Comment by lmasdata** [comment]
ok 多谢

**Comment by wuhuajie** [comment]
Fixed.

components/uploader.vue 里面
<input v-if="!handleClick" ref="input" class="weui-uploader__input" type="file" accept="image/image/jpg,image/jpeg,image/png,image/gif" :capture="showCapture" @change="change">

改为

<input v-if="!handleClick" ref="input" class="weui-uploader__input" type="file" accept="image/*" :capture="showCapture" @change="change">

**Comment by greedying** [comment]
你好，是不是选择得jpg图片？我看jpg图片之前的代码好像有问题




| |
王叶深
邮箱：greedying@163.com
|

签名由 网易邮箱大师 定制

在2018年01月12日 19:09，wuhuajie 写道：

Fixed.

components/uploader.vue 里面
<input v-if="!handleClick" ref="input" class="weui-uploader__input" type="file" accept="image/image/jpg,image/jpeg,image/png,image/gif" :capture="showCapture" @change="change">

改为

<input v-if="!handleClick" ref="input" class="weui-uploader__input" type="file" accept="image/*" :capture="showCapture" @change="change">

**Comment by wuhuajie** [comment]
是为了解决安卓手机只能打开相册不能拍照

**Comment by greedying** [comment]
@wuhuajie 之前写法是为了解决chrome下的延迟问题。不过移动端，chrome可以先不考虑。欢迎PR哦
