### ISSUE TITLE
默认上传文件流的name是img,有自定义方案么？

### ISSUE THREAD

**Issue by daledelv** [greedying/vux-uploader#21]
如题

**Comment by greedying** [comment]
欢迎PR


| |
王叶深
邮箱：greedying@163.com
|

签名由 网易邮箱大师 定制

在2018年01月16日 14:49，dally_G 写道：

如题

**Comment by greedying** [comment]
fixed [67bc9d1](https://github.com/greedying/vux-uploader/commit/67bc9d1d93e1cdcccab7e742f9ab9596d0b3922a)
