### ISSUE TITLE
IOS点击+ 会弹窗从相册选择或拍照，拍照有问题

### ISSUE THREAD

**Issue by SimonVampire** [greedying/vux-uploader#23]
IOS点击+ 会弹窗从相册选择或拍照，从相册选择OK， 拍照拍完后，控件没响应怎么弄。   貌似无相关介绍呀。

**Comment by greedying** [comment]
请提供相关代码


| |
王叶深
邮箱：greedying@163.com
|

签名由 网易邮箱大师 定制

在2018年02月07日 17:53，SimonVampire 写道：

IOS点击+ 会弹窗从相册选择或拍照，从相册选择OK， 拍照拍完后，控件没响应怎么弄。 貌似无相关介绍呀。

**Comment by SimonVampire** [comment]
邮件已发  请帮忙看看

**Comment by SimonVampire** [comment]
<uploader :readonly="false" :max="1" :images="gzImages" :withCredentials="false" :span="4"
                      :autoUpload="false" @preview="previewImg" @upload-image="uploadPic" @remove-image="deletePic">
            </uploader>

**Comment by greedying** [comment]
这个代码没看出有什么问题哦~~无法判定。理论上拍照还是选择照片，对程序是没区别的
