### ISSUE TITLE
打包成apk在安卓系统运行不支持 type=file

### ISSUE THREAD

**Issue by limnQQ** [greedying/vux-uploader#27]
打包成apk在安卓系统运行不支持 type=file，请问怎么解决

**Comment by greedying** [comment]
这个暂时超出我知识范围了


| |
王叶深
邮箱：greedying@163.com
|

签名由 网易邮箱大师 定制

在2018年04月04日 11:51，limnQQ 写道：

打包成apk在安卓系统运行不支持 type=file

**Comment by greedying** [comment]
你好，有人反馈说这个是因为 需要手动在android监听 file 选择事件。我不懂android，供参考
