### ISSUE TITLE
选择图片之后图片没显示出来怎么解决

### ISSUE THREAD

**Issue by lanjincan** [greedying/vux-uploader#30]
<uploader
      :max="3"
      :images="images"
      :title="'请选择现场图片'"
      :handle-click="false"
      :show-header="true"
      :readonly="false"
      :auto-upload="false"
      class="photo-sign-uploader"
    ></uploader>

 data(){
      return{
        varmax: 5,
        images: [],
        uploadUrl: ''

      }
    },

**Comment by lanjincan** [comment]
<uploader
      :max="3"
      :images="images"
      :title="'请选择现场图片'"
      :handle-click="false"
      :show-header="true"
      :readonly="false"
      :auto-upload="false"
      class="photo-sign-uploader"
    ></uploader>

**Comment by greedying** [comment]
信息太少，没法判断具体原因

**Comment by Likeag6xx** [comment]
请问解决了吗？
