### ISSUE TITLE
页面未报错 但是页面显示空白，F12确实该区域有相关元素

### ISSUE THREAD

**Issue by shen-lan** [greedying/vux-uploader#33]
```
                <uploader
                    :max="maxImg"
                    :images="images"
                    :handle-click="true"
                    :show-header="false"
                    :readonly="true"
                    :upload-url="uploadUrl"
                    name="img"
                    :params="params"
                    size="small"
                    @preview="previewMethod"
                    @add-image="addImageMethod"
                    @remove-image="removeImageMethod"
                ></uploader> 
```

**Comment by shen-lan** [comment]
F12后发现这些元素都是display:none

**Comment by a497556016** [comment]
一样的问题

**Comment by cj12580** [comment]
同样的问题 作者为什么不回复

**Comment by shen-lan** [comment]
楼上的兄弟们，不要问了。他这个上传组件必须看源码灵活使用。你如果想拿来就用，简单方便，抱歉，这个不合适。否则，推荐使用这个    https://github.com/watson-yan/vue-uploader
这个很简单，开箱即用。实际使用，可能需要压缩。百度cavas压缩上传图片。稍微改造下即可。

**Comment by greedying** [comment]
😄类似问题之前回复过，请自行搜索。另外用法本来就应该自己看文档。而且我也不反对大家推荐其他插件




| |
王叶深
邮箱：greedying@163.com
|

签名由 网易邮箱大师 定制

在2018年06月22日 18:23，shen-lan 写道：

楼上的兄弟们，不要问了。他这个上传组件必须看源码灵活使用。你如果想拿来就用，简单方便，抱歉，这个不合适。否则，推荐使用这个https://github.com/watson-yan/vue-uploader，这个很简单，开箱即用。实际使用，可能需要压缩。百度cavas压缩上传图片。稍微改造下即可。

**Comment by greedying** [comment]
或者，谁可以建一个demo，去掉逻辑代码发上来看看。现在这样子，的确没法查啊。
