### ISSUE TITLE
autoUpload配置为false时，$emit('upload-image', formData)，formData无数据？

### ISSUE THREAD

**Issue by lonlie** [greedying/vux-uploader#36]
autoUpload配置为false时，$emit('upload-image', formData)，formData无数据？
`<uploader :max="1" :autoUpload="false" ref="upload" @upload-image="uploadImage"></uploader>`
`uploadImage: function(data) {
      console.log(data) // FormData {}
    }`

这什么情况？

**Comment by greedying** [comment]
:auto-upload="false"
