### ISSUE TITLE
在开发环境无论是选择自动上传还是手动上传，都会提示没有选择文件

### ISSUE THREAD

**Issue by XdyGoGo** [greedying/vux-uploader#40]

**Comment by greedying** [comment]
你好，可否建立一个demo重现一下？然后github 贴一下，谢谢

**Comment by XdyGoGo** [comment]
// 接管图片上传过程，手动上传，图片质量压缩
    uploadImage(formData) {
      let vm = this
      let file = formData.get('img')
      let fileName = file.name
      let reader = new FileReader()
      let img = new Image()
      let canvas = document.createElement('canvas')
      let ctx = canvas.getContext('2d')
      let imgType = /^image\/[jpeg|png|gif]/i
      const MAX_SIZE = 5
      if (!imgType.test(file.type)) {
        console.log('非图片！')
        return 
      } else if (file.size > MAX_SIZE * 1024 * 1024) {
        console.log('太大了！')
        return
      }
      reader.onload = function() {
        img.src = this.result
        img.onload = function() {
          let imgW = this.width,
              imgH = this.height
          if (imgW > imgH && imgW > 640) {
            imgW = 640
            imgH = Math.ceil(750 * this.height / this.width)
          } else if (imgW < imgH && imgH > 1334) {
            imgW = Math.ceil(1334 * this.width / this.height)
            imgH = 1334
          }
          canvas.width = imgW
          canvas.height = imgH

          let finalImg = canvas.toDataURL(file.type, 0.88)
          let ajaxFile = vm.dataURItoBlob(finalImg)  
          vm.sendImg(ajaxFile, fileName)  // 图片上传
        }
      }
      reader.readAsDataURL(file)
    },
    // 将压缩的base64转二进制文件
    dataURItoBlob(dataURI) {
        var byteString = atob(dataURI.split(',')[1]);
        var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
        var ab = new ArrayBuffer(byteString.length);
        var ia = new Uint8Array(ab);
        for (var i = 0; i < byteString.length; i++) {
            ia[i] = byteString.charCodeAt(i);
        }
        return new Blob([ab], {type: mimeString});
    },
    // 图片上传接口
    sendImg(img, fileName) {
        console.log(img)
        let form = new FormData()
        form.append('img', img, fileName)
        AjaxPlugin.$http.post(this.uploadUrl, form)
              .then(res => {
                  this.$refs.uploaderHook[0].$el.getElementsByClassName('weui-uploader__input')[0].value = ''
                  this.imagesList.push(res.data.data)
              })
              .catch(err => {
                  console.log(err)
              })
    },

**Comment by XdyGoGo** [comment]
<uploader class="uploader-wrapper"
              :max=3
              title="上传图片"
              :handle-click="false"
              :show-header="true"
              :readonly="false"
              :upload-url="uploadUrl"
              size="normal"
              :autoUpload="false"
              @upload-image="uploadImage"
              :image="imagesList"
              ref="uploaderHook"
              ></uploader>

**Comment by greedying** [comment]
:auto-upload="false" ？

**Comment by XdyGoGo** [comment]
为true也一样哦

**Comment by XdyGoGo** [comment]
style="background-image: url("");" 貌似是src没有成功赋值

**Comment by greedying** [comment]
最好建一个没有业务逻辑代码的项目。这样看代码没法查的




| |
王叶深
邮箱：greedying@163.com
|

签名由 网易邮箱大师 定制

在2018年10月11日 11:35，XdyGoGo 写道：

style="background-image: url("");" 貌似是src没有成功赋值

**Comment by XdyGoGo** [comment]
好的

**Comment by XdyGoGo** [comment]
大概知道什么问题了 就是这里会报错  uploadImage(formData) {
      let vm = this
      let file = formData.get('img')
      let fileName = file.name
