### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by felixjing** [greedying/vux-uploader#6]
![wechatimg534](https://cloud.githubusercontent.com/assets/2263638/25062433/9b0da5da-21fe-11e7-94a6-bf4fbfa53888.jpg)
移动网络下，图片过大，上传是有时会一直loading，但图片其实已经传到服务器上了。
是几率发生，不清楚是不是哪个地方超时的问题

另：
手机上传多张图片的时候，上传成功一张之后，比如在上传第二张的时候，到了选择图片界面，如果不选择图片直接点手机返回按钮，依然触发了上传操作，会产生错误。

另：
一张图片好像没法传两次，如果一张图片已经上传，但不小心点了"-"，再选择的话就不能上传了

**Comment by greedying** [comment]
1、 大图，麻烦抓包看下返回结果，否则不好确认。另外是通过哪种方式上传也需要说明
2、这个我看下
3、最新版已经解决了这个问题

**Comment by felixjing** [comment]
建议增加图片优化，处理大小后再上传。手机拍照的图一般都挺大

**Comment by greedying** [comment]
:-(，欢迎pr。最近较忙，一直没时间写- -

**Comment by lanjincan** [comment]
这个正在上传的loading怎么做的？自动上传

**Comment by huangjieqiu** [comment]
为啥没有提供上传图片成功的回调函数呢

**Comment by greedying** [comment]
@lanjincan 使用的vux的loading插件。

**Comment by greedying** [comment]
@huangjieqiu 可以自己接管上传流程，或者watch 图片数组
