### ISSUE TITLE
我觉得做个DEMO和效果演示是极好的

### ISSUE THREAD

**Issue by walijoy** [greedying/vux-uploader#9]
RTRT

**Comment by greedying** [comment]
欢迎PR~~ demo的问题在于，还需要一个后端接口，也就需要一台服务器。略显浪费。

**Comment by wangtifang** [comment]
可以不要后端嘛。只要前端

**Comment by yeh110** [comment]
可以考虑下免费的七牛云 10G空间

**Comment by greedying** [comment]
谢谢。其实我觉得没必要做嘿嘿




| |
王叶深
邮箱：greedying@163.com
|

签名由 网易邮箱大师 定制

在2018年07月13日 22:59，Circle 写道：

可以考虑下免费的七牛云 10G空间
